# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Filipp Keks"
description: > # this means to ignore newlines until "email:"
   tech blog

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/iceland.jpg"

name: 'Filipp Keks'
author: 'Filipp Keks'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.filippkeks.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@taphos'
facebook_appid: '1619144488394835'

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/taphos
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/taphos
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
