# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Filipp Keks"
description: > # this means to ignore newlines until "email:"
   tech blog

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/iceland.jpg"

name: 'Filipp Keks'
author: 'Filipp Keks'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.filippkeks.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@taphos'
facebook_appid: '1619144488394835'
